# Generated by Django 4.0.3 on 2022-04-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
